# -*- coding: utf-8 -*-
"""PageScrapper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t7R2XgcqBLR_wrsvvBisto2DR5x092IX
"""

import requests

link = 'http://quotes.toscrape.com/'

res = requests.get(link)

res

html = res.text

html

print(html)

fd = open('main.html','w')
fd.write(html)
fd.close()
